
/**
 *
 * @author Israel Basurto
 */

public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Hallowen UVEG...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jblFondo2 = new javax.swing.JLabel();
        btnAbrir = new javax.swing.JButton();
        lblFondo3 = new javax.swing.JLabel();
        jlbFondo5 = new javax.swing.JLabel();
        jlb6 = new javax.swing.JLabel();
        jlb7 = new javax.swing.JLabel();
        jlb9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlb11 = new javax.swing.JLabel();
        jlb10 = new javax.swing.JLabel();
        jlb12 = new javax.swing.JLabel();
        jlbFondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halloween");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/diamuertos.jpg"))); // NOI18N
        jblFondo2.setText("jLabel1");
        jblFondo2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jblFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 390, 130));

        btnAbrir.setBackground(new java.awt.Color(0, 0, 51));
        btnAbrir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnAbrir.setForeground(new java.awt.Color(102, 0, 0));
        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        lblFondo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pumpkin_evil_halloween_21550.png"))); // NOI18N
        jPanel1.add(lblFondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 120, 90));

        jlbFondo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pumpkins_all_halloween_21552.png"))); // NOI18N
        jPanel1.add(jlbFondo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 260, 280));

        jlb6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/chaudron_halloween_21539.png"))); // NOI18N
        jPanel1.add(jlb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 160, 130));

        jlb7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/spider_halloween_23218.png"))); // NOI18N
        jPanel1.add(jlb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 150, 180));

        jlb9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bonbon_orange_halloween_21533.png"))); // NOI18N
        jPanel1.add(jlb9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bonbon_green_halloween_21532.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 160));

        jlb11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/skeleton_halloween_23220.png"))); // NOI18N
        jPanel1.add(jlb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 150, 180));

        jlb10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/broom_halloween_21535.png"))); // NOI18N
        jPanel1.add(jlb10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 150, 180));

        jlb12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bonbon_wblack_halloween_21534.png"))); // NOI18N
        jPanel1.add(jlb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, 180));

        jlbFondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/art_calavera.jpg"))); // NOI18N
        jPanel1.add(jlbFondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        Ventana2 newframe = new Ventana2();        
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblFondo2;
    private javax.swing.JLabel jlb10;
    private javax.swing.JLabel jlb11;
    private javax.swing.JLabel jlb12;
    private javax.swing.JLabel jlb6;
    private javax.swing.JLabel jlb7;
    private javax.swing.JLabel jlb9;
    private javax.swing.JLabel jlbFondo4;
    private javax.swing.JLabel jlbFondo5;
    private javax.swing.JLabel lblFondo3;
    // End of variables declaration//GEN-END:variables
}
