
import CalveritaUVEG.Ventana3;
import javax.swing.JOptionPane;

/**
 *
 * @author Israel Basurto
 */

public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("UVEG");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMostrar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnVentana3 = new javax.swing.JButton();
        jblFondo2 = new javax.swing.JLabel();
        jlb4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlb5 = new javax.swing.JLabel();
        jlb6 = new javax.swing.JLabel();
        jlb7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jblFondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMostrar.setBackground(new java.awt.Color(0, 0, 51));
        btnMostrar.setForeground(new java.awt.Color(0, 0, 255));
        btnMostrar.setText("Mostrar mensaje");
        btnMostrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, -1, -1));

        btnInicio.setBackground(new java.awt.Color(0, 0, 51));
        btnInicio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(102, 0, 0));
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 80, 30));

        btnVentana3.setBackground(new java.awt.Color(0, 0, 51));
        btnVentana3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnVentana3.setForeground(new java.awt.Color(102, 0, 0));
        btnVentana3.setText("Fin");
        btnVentana3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentana3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentana3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 80, 30));

        jblFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/uveg_logo1.jpg"))); // NOI18N
        jblFondo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jblFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 280, 170));

        jlb4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bonbon_orange_halloween_21533.png"))); // NOI18N
        jPanel1.add(jlb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 200, 130));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/hat_halloween_21547.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 140, 180));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cat_halloween_23230.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 270, 260));

        jlb5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/halloween_tree_halloween_21546.png"))); // NOI18N
        jPanel1.add(jlb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 310, 310));

        jlb6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/chaudron_halloween_21539.png"))); // NOI18N
        jPanel1.add(jlb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 200, 130));

        jlb7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/mask_halloween_23223.png"))); // NOI18N
        jPanel1.add(jlb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, 200, 130));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/spider_halloween_23218.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 210, 110));

        jblFondo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/uveg_23_3d_nuevo.png"))); // NOI18N
        jPanel1.add(jblFondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        JOptionPane.showMessageDialog(rootPane, "<html><h1 align='center'><font color='blue'>&#128519;&#128519;&#128519;&#128519;&#128519;&#128519;&#128519;&#128519;&#128519;</h1><h2><font color='blue'><font color='red'> FELICES FIESTAS LES DESEA LA <font color='blue'> UVEG ","",JOptionPane.PLAIN_MESSAGE);
        JOptionPane.showMessageDialog(rootPane, "<html><h1 align='center'><font color='red'>&#128520;&#128520;&#128520;&#128520;&#128520;&#128520;&#128520;&#128520;&#128520;&#128520;</h1><h2><font color='purple'> Calaverita UVEG.... <font color='red'> Los estudiantes de la UVEG, Tenian miedo de la Muerte,Pero UVEG se hizo presente... ","",JOptionPane.PLAIN_MESSAGE);
        JOptionPane.showMessageDialog(rootPane, "<html><h1 align='center'><font color='red'>&#128520;&#128520;&#128520;&#128520;&#128520;&#128520;&#128520;&#128520;&#128520;&#128520;</h1><h2><font color='red'>Para que perdiran ese miedo a la muerte,Mediante tareas y retos,Que su mente volo mas alla de su coeficiente...","",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        Inicio newframe = new Inicio();        
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnVentana3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentana3ActionPerformed
        Ventana3 newframe = new Ventana3();        
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentana3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVentana3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblFondo2;
    private javax.swing.JLabel jblFondo3;
    private javax.swing.JLabel jlb4;
    private javax.swing.JLabel jlb5;
    private javax.swing.JLabel jlb6;
    private javax.swing.JLabel jlb7;
    // End of variables declaration//GEN-END:variables
}
